language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs
  - vendor/bin/phpstan analyse -l 4 src
  - vendor/bin/phpunit

cache:
    directories:
        - $HOME/.composer/cache
